version: '3'
services:
  cadadora_auth:
    container_name: cadadora_auth
    image: cadadora_auth:1.0.1
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    build:
       context: .
       dockerfile: ./Dockerfile.AuthServer
    restart: always
    ports:
      - 55334:80
    depends_on:
      - redis
  cadadora_backend:
    container_name: cadadora_backend
    image: cadadora_backend:1.0.1
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    build:
        context: .
    restart: always
    ports:
        - 5000:80
    depends_on:
        - redis
        - cadadora_auth
networks: 
    external: 
      name: srv-network